# Generated by Django 3.2 on 2022-07-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrameshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
    ]
