# Generated by Django 3.2 on 2022-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrameshop', '0002_rename_name_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
