# Generated by Django 3.2 on 2022-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcrudapp', '0005_auto_20220817_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='testcrudapp.Tag'),
        ),
    ]
